### PR TITLE
Fature branch

### PR DESCRIPTION
**Pull request by zdrale**
This is the 5th project on the main curriculum. It is built using Html and CSS. This is a page that resembles design of Smasing Magazin front page. The project contains the following components:
.Header section 
.Banner section 
.Main section
.Footer section is positioned using Flex

### CODE REVIEW

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @cyonii and @zdrale
Such a remarkable project you made :+1: !
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes  👇.
- [x] Fix Linter issues
- [x] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/94562768-2e8c9780-027f-11eb-8d30-3ac1d769d6a8.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/) ([screenshot](https://user-images.githubusercontent.com/29689273/94326203-fa358480-ffbb-11ea-81ec-b2704fb93212.png) from Pathwright)
- [ ] Navbar uses `nav` element with `ul/li` inside, however, students are allowed to used div as the main focus is a heat map
- [ ] Footer contains centered links

- [ ] **[OPTIONAL]** Add hover effect on `avatar`
- **[Advise]** It's not good enough to close/merge PR that has been reviewed and not yet approved. If you have merged by mistake or another reason, please Explain it in the Description with giving the reference of previous Pull Request

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @cyonii and @zdrale
Such a remarkable project you made :+1: !
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly work on the suggested changes  👇.

- [x] Navbar uses `nav` element with `ul/li` inside, however, students are allowed to used div as the main focus is a heat map
**Explanation:** Every TSE mentions this in his review for this project. In the clone project you are using `div` for navbar items, and not using the `nav` tag. So make within the nav tag use `ul/li` for navbar items
- [x] Footer contains centered links
**Explanation:** In the footer you are using div's please visit the original page and align the footer items according to the original webpage and use the `anchor` tag or `ul` tag
- [x] **[OPTIONAL]** Add hover effect on `avatar`

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great job working on the previously required changes!! :clap: :clap: :clap:

## Required Changes
### [Mandatory] :red_circle: 

- [x] There should be only one nav in the document. The footer ```<nav>``` can be converted into an ```<ul>```

- [x] Use ```<main>``` to wrap the content that doesn't belong to the header nor the foot.

### [OPTIONAL]

- [ ] The README file should have a short description of the project's goals.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Review by arslanbisharat — APPROVED** [review]
## Approved 
Thank you for making all the changes requested by previous TSEs.
Please merge the branch and move forward with your curriculum.
**Arslan Bisharat**

**Pull request merged**
